name: Test PR

on:
  pull_request:
    paths:
      - "lib/**"
    branches:
      - "**"

env:
  LIB_DIR: lib

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      
      - name: Install dependencies
        run: yarn install
        working-directory: ${{ env.LIB_DIR }}

      - name: Build and Lint 
        run: yarn lint && yarn build
        working-directory: ${{ env.LIB_DIR }}