name: Publish the package

on:
  push:
    branches:
      - main
    paths:
      - 'lib/**'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - run: yarn install --frozen-lockfile
      - name: Create pull request or publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn run build
