name: Publish the package

on:
  push:
    branches:
      - main
    paths:
      - 'packages/lib/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  LIB_DIR: packages/lib

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Yarn Install
        working-directory: ${{ env.LIB_DIR }}
        run: yarn install


      - name: Create pull request or publish
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          publish: yarn run build && yarn changeset publish
          cwd: "./packages/lib"
